# -*- coding: utf-8 -*-
"""CAC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DAxTnB781v8I9FIQTpOLnOs17jZXwqJQ
"""

!pip install -q pandas-profiling
!pip install -q tensorflow

# Commented out IPython magic to ensure Python compatibility.
# Basic data handling
import pandas as pd
import numpy as np

# Data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine learning preprocessing & modeling
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, LogisticRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.metrics import mean_absolute_error, r2_score, classification_report, confusion_matrix, accuracy_score

# Deep learning
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

# Stats and Probabilistic Models
from scipy import stats

# Profiling
# from pandas_profiling import ProfileReport # Removed due to AttributeError

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

# Inline plots (default in Colab)
# %matplotlib inline

"""# Task
Explain the error in the selected code, fix it if possible, and generate a pandas profiling report for the data.

## Update `joblib`

### Subtask:
Update the `joblib` library to a version compatible with `scikit-learn`.

**Reasoning**:
Upgrade the `joblib` library using pip to resolve the dependency conflict with scikit-learn.
"""

!pip install -q joblib>=1.2.0

"""## Reinstall `pandas-profiling`

### Subtask:
Reinstall `pandas-profiling` after updating `joblib` to potentially resolve dependency conflicts.

**Reasoning**:
Uninstalling and reinstalling `pandas-profiling` might resolve the dependency conflict seen earlier with `scikit-learn` and `joblib` after updating `joblib`.
"""

!pip uninstall -y pandas-profiling
!pip install -q pandas-profiling

"""## Generate profile report

### Subtask:
Import `ProfileReport` from `pandas_profiling` and generate the profile report for your data.

**Reasoning**:
Import ProfileReport and generate the profile report for the dataframe.

**Reasoning**:
The traceback indicates an AttributeError within the `visions` library, which is a dependency of `pandas-profiling`. Specifically, it's looking for `generated_jit` in the `numba` module. This suggests an incompatibility between the installed versions of `numba` and `visions`. To fix this, I will uninstall `numba` and then reinstall `pandas-profiling`, which should install a compatible version of `numba` as a dependency.
"""

!pip uninstall -y numba
!pip install -q pandas-profiling

"""**Reasoning**:
Now that the potential compatibility issue with `numba` has been addressed by reinstalling `pandas-profiling`, I will attempt to import `ProfileReport` and generate the profile report again.

**Reasoning**:
Despite reinstalling `pandas-profiling`, the `AttributeError` related to `numba.generated_jit` persists. This indicates a deeper incompatibility issue, likely with the `visions` library which is a dependency of `pandas-profiling`. Since directly resolving dependency conflicts of complex packages can be challenging and `pandas-profiling` is now deprecated in favor of `ydata-profiling`, it's more practical to switch to the recommended library. Therefore, I will install `ydata-profiling` and use it to generate the profile report.

**Reasoning**:
The traceback shows a `NameError` because the `df` variable was not defined in the current execution context. While the `ydata-profiling` installation was successful and produced a display object, the code execution was interrupted by the `NameError` before the profile report could be fully generated and displayed. I need to recreate the dummy DataFrame `df` before generating the profile report with `ydata-profiling`.
"""

!pip install -q ydata-profiling

import pandas as pd
from ydata_profiling import ProfileReport

# Load CSVs into DataFrames
df_bookings = pd.read_csv("fact_bookings.csv")
df_agg_bookings = pd.read_csv("fact_aggregated_bookings.csv")
df_rooms = pd.read_csv("dim_rooms.csv")
df_hotels = pd.read_csv("dim_hotels.csv")
df_date = pd.read_csv("dim_date.csv")

# List of all DataFrames
dfs = {
    "Bookings": df_bookings,
    "Aggregated Bookings": df_agg_bookings,
    "Rooms": df_rooms,
    "Hotels": df_hotels,
    "Date": df_date
}

# Explore each dataset
for name, df in dfs.items():
    print(f"\n{'='*30}\n{name.upper()} DATA\n{'='*30}")
    print("Shape:", df.shape)
    print("\nHEAD:\n", df.head())
    print("\nINFO:\n")
    print(df.info())
    print("\nMissing values:\n", df.isnull().sum())
    print("\nDESCRIBE (numerical):\n", df.describe())

# First, check unique values in booking status
print("Unique Booking Status Values:")
print(df_bookings['booking_status'].value_counts())

# Create subsets based on status
df_cancelled = df_bookings[df_bookings['booking_status'].str.lower() == 'cancelled']
df_checkedout = df_bookings[df_bookings['booking_status'].str.lower() == 'checked_out']
df_noshow = df_bookings[df_bookings['booking_status'].str.lower() == 'no_show']

# Print counts
print("\nNumber of Cancelled Bookings:", df_cancelled.shape[0])
print("Number of Checked-Out Bookings:", df_checkedout.shape[0])
print("Number of No-Show Bookings:", df_noshow.shape[0])

import seaborn as sns
import matplotlib.pyplot as plt

# Set plot style
sns.set(style="whitegrid")

# Plot booking status distribution
plt.figure(figsize=(8, 5))
sns.countplot(data=df_bookings, x='booking_status', palette='pastel')
plt.title("Booking Status Distribution")
plt.xlabel("Booking Status")
plt.ylabel("Number of Bookings")
plt.show()

df_cancelled.to_csv("cancelled_bookings.csv", index=False)
df_checkedout.to_csv("checked_out_bookings.csv", index=False)
df_noshow.to_csv("no_show_bookings.csv", index=False)

# Check column types
df_bookings.dtypes

from sklearn.preprocessing import LabelEncoder

# Create a copy to avoid overwriting raw data
df_encoded = df_bookings.copy()

# Apply label encoding to selected categorical columns
label_enc_cols = ['property_id', 'room_category', 'booking_platform', 'booking_status']

label_encoders = {}

for col in label_enc_cols:
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df_encoded[col].astype(str))
    label_encoders[col] = le  # Save encoder for inverse_transform later if needed

# Convert dates to datetime
df_encoded['booking_date'] = pd.to_datetime(df_encoded['booking_date'])
df_encoded['check_in_date'] = pd.to_datetime(df_encoded['check_in_date'])
df_encoded['checkout_date'] = pd.to_datetime(df_encoded['checkout_date'])

# New date-based features
df_encoded['booking_weekday'] = df_encoded['booking_date'].dt.weekday
df_encoded['checkin_weekday'] = df_encoded['check_in_date'].dt.weekday
df_encoded['stay_duration'] = (df_encoded['checkout_date'] - df_encoded['check_in_date']).dt.days
df_encoded['advance_booking_days'] = (df_encoded['check_in_date'] - df_encoded['booking_date']).dt.days

# Weekend/Weekday flags (0 = Weekday, 1 = Weekend)
df_encoded['is_weekend_booking'] = df_encoded['booking_weekday'].apply(lambda x: 1 if x >= 5 else 0)
df_encoded['is_weekend_checkin'] = df_encoded['checkin_weekday'].apply(lambda x: 1 if x >= 5 else 0)

df_encoded[['booking_weekday', 'checkin_weekday', 'stay_duration', 'advance_booking_days', 'is_weekend_booking']].head()

# Set plot style
sns.set(style="darkgrid")

# Plot: Distribution of Ratings
plt.figure(figsize=(8,5))
sns.histplot(df_encoded['ratings_given'], kde=True, bins=20)
plt.title("Distribution of Ratings")
plt.xlabel("Rating")
plt.ylabel("Frequency")
plt.show()

# Plot: Booking Status Count
plt.figure(figsize=(6,4))
sns.countplot(data=df_encoded, x='booking_status')
plt.title("Booking Status Count")
plt.ylabel("Number of Bookings")
plt.show()

# Plot: Room Category Count
plt.figure(figsize=(6,4))
sns.countplot(data=df_encoded, x='room_category')
plt.title("Room Category Distribution")
plt.ylabel("Count")
plt.show()

# Plot: Advance Booking Days
plt.figure(figsize=(8,5))
sns.histplot(df_encoded['advance_booking_days'], kde=True)
plt.title("Advance Booking Days Distribution")
plt.xlabel("Days before check-in")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(data=df_encoded, x='booking_status', y='revenue_realized')
plt.title("Revenue Realized vs Booking Status")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(data=df_encoded, x='ratings_given', y='revenue_realized', hue='room_category')
plt.title("Ratings vs Revenue Realized (by Room Category)")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(data=df_encoded, x='booking_status', y='advance_booking_days')
plt.title("Booking Status vs Advance Booking Days")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(data=df_encoded, x='no_guests', y='revenue_realized')
plt.title("Guests vs Revenue Realized")
plt.show()

# Correlation matrix (only numeric)
plt.figure(figsize=(12,8))
corr = df_encoded.corr(numeric_only=True)
sns.heatmap(corr, annot=True, fmt=".2f", cmap='coolwarm')
plt.title("Feature Correlation Heatmap")
plt.show()

from ydata_profiling import ProfileReport

# Generate the profile report from the encoded dataset
profile = ProfileReport(df_encoded, title="Hotel Booking EDA Report", explorative=True)

# Export it to HTML (download this manually in Colab after rendering)
profile.to_file("hotel_booking_eda_report.html")

from google.colab import files
files.download("hotel_booking_eda_report.html")

"""Model 1: Revenue Prediction (Regression)
Objective: Predict revenue_realized based on booking behavior and hotel features.

Model 2: Cancellation Prediction (Classification)
Objective: Predict whether a booking will be cancelled or not

"""

# Make a copy for modeling
df_model = df_encoded.copy()

# Drop columns we don't want to use directly
drop_cols = ['booking_id', 'booking_date', 'check_in_date', 'checkout_date', 'revenue_generated']
df_model = df_model.drop(columns=drop_cols)

# Drop rows where revenue_realized is NaN (just in case)
df_model = df_model.dropna(subset=['revenue_realized'])

# Select Features
features = [
    'property_id',
    'room_category',
    'booking_platform',
    'no_guests',
    'ratings_given',
    'booking_status',
    'booking_weekday',
    'checkin_weekday',
    'stay_duration',
    'advance_booking_days',
    'is_weekend_booking',
    'is_weekend_checkin'
]

# Drop rows where ratings are missing for now (can be handled differently later)
df_model = df_model.dropna(subset=['ratings_given'])

X = df_model[features]
y = df_model['revenue_realized']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Initialize models
lr = LinearRegression()
ridge = Ridge()
lasso = Lasso()
rf = RandomForestRegressor(random_state=42)

# Dictionary of models
models = {
    'Linear Regression': lr,
    'Ridge Regression': ridge,
    'Lasso Regression': lasso,
    'Random Forest': rf
}

# Train & Evaluate
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print(f"\nModel: {name}")
    print("R2 Score:", round(r2_score(y_test, y_pred), 3))
    print("RMSE:", round(mean_squared_error(y_test, y_pred), 2))

# Encode target
df_cancel_model = df_encoded[df_encoded['booking_status'].isin(['cancelled', 'checked_out'])].copy()
df_cancel_model['is_cancelled'] = df_cancel_model['booking_status'].apply(lambda x: 1 if x == 'cancelled' else 0)

# Drop columns safely
drop_cols = [
    'booking_id', 'booking_date', 'check_in_date', 'checkout_date',
    'revenue_realized', 'revenue_generated', 'booking_status'
]
df_cancel_model = df_cancel_model.drop(columns=drop_cols, errors='ignore')

# Drop rows with missing essential features
essential_features = ['property_id', 'no_guests', 'room_category', 'booking_platform']
df_cancel_model = df_cancel_model.dropna(subset=essential_features)

# Fill ratings_given missing with -1
df_cancel_model['ratings_given'] = df_cancel_model['ratings_given'].fillna(-1)

# Check result
print("Final shape:", df_cancel_model.shape)

# Define features and target
X_cancel = df_cancel_model.drop(columns=['is_cancelled'])
y_cancel = df_cancel_model['is_cancelled']















#Thank you

"""## Summary:

### Data Analysis Key Findings

*   Upgrading `joblib` to version 1.2.0 or higher was successfully completed.
*   `pandas-profiling` was uninstalled and reinstalled.
*   Generating the profile report using `pandas-profiling` initially failed due to an `AttributeError` related to `numba.generated_jit`.
*   Switching from `pandas-profiling` to `ydata-profiling` resolved the `numba` compatibility issue.
*   A `NameError` occurred when using `ydata-profiling` because the DataFrame `df` was not defined in the new execution environment.
*   A dummy DataFrame was created, and the profile report was successfully generated and displayed using `ydata-profiling`.

### Insights or Next Steps

*   When encountering dependency issues with libraries like `pandas-profiling`, consider if there is a recommended successor library, such as `ydata-profiling`, that may have better dependency management.
*   Ensure all necessary data structures (like DataFrames) are defined within the active execution environment before attempting to perform operations on them.

"""