# -*- coding: utf-8 -*-
"""Hospitality Sector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZzqEPIubFBNCpC1XJNv7iDXBK9Dm3EWp
"""

#import libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#upload data
from google.colab import files
uploaded = files.upload()

# Read the entire Excel file
excel_file = pd.ExcelFile('All Data.xlsx')

# To see the names of the sheets
print(excel_file.sheet_names)

# Assign each sheet to a separate variable
date_df = pd.read_excel(excel_file, sheet_name='dim_date')
hotel_df = pd.read_excel(excel_file, sheet_name='dim_hotel')
room_df = pd.read_excel(excel_file, sheet_name='dim_rooms')
occupancy_df = pd.read_excel(excel_file, sheet_name='fact_aggregated_bookings')
bookings_df = pd.read_excel(excel_file, sheet_name='fact_bookings')

#understanding the data
print("Sheet 1 Preview:")
print(date_df.head())

print("\nSheet 2 Preview:")
print(hotel_df.head())

print("\nSheet 3 Preview:")
print(room_df.head())

print("\nSheet 4 Preview:")
print(occupancy_df.head())

print("\nSheet 5 Preview:")
print(bookings_df.head())

#understanding the data
print(date_df.info(), "\n")
print(hotel_df.info(), "\n")
print(room_df.info(), "\n")
print(occupancy_df.info(), "\n")
print(bookings_df.info(), "\n")

# Correction of format of column 2 in date_df sheet
date_df['mmm yy'] = date_df['date'].dt.strftime('%b %y')

print(date_df[['date', 'mmm yy']].head())

#creating a primary key in occupancy_sheet
occupancy_df['date_str'] = occupancy_df['check_in_date'].dt.strftime('%b%d%y').str.lower()

occupancy_df['property_str'] = occupancy_df['property_id'].astype(str)

occupancy_df['occupancy_id'] = (
    occupancy_df['date_str'] +
    occupancy_df['property_str'] +
    occupancy_df['room_category']
)

occupancy_df.drop(columns=['date_str', 'property_str'], inplace=True)

print(occupancy_df[['occupancy_id']].head())

cols = occupancy_df.columns.tolist()
cols.insert(0, cols.pop(cols.index('occupancy_id')))
occupancy_df = occupancy_df[cols]

# Standerdising column names
room_df.rename(columns={'room_id': 'room_category'}, inplace=True)
occupancy_df.rename(columns={'check_in_date': 'date'}, inplace=True)

# Checking for duplicates
print(occupancy_df['occupancy_id'].duplicated().sum())
print(bookings_df['booking_id'].duplicated().sum())

bookings_per_day = bookings_df.groupby('check_in_date').size()
bookings_per_day.plot(kind='line', title='Bookings Over Time')

# Total bookings
total_bookings = bookings_df.groupby('check_in_date').size()

# Cancellations
cancelled = bookings_df[bookings_df['booking_status'].str.lower() == 'cancelled']
cancelled_bookings = cancelled.groupby('check_in_date').size()

# Reindex all to the same date range (fill missing dates with 0)
all_dates = pd.date_range(start=bookings_df['check_in_date'].min(), end=bookings_df['check_in_date'].max())
total_bookings = total_bookings.reindex(all_dates, fill_value=0)
cancelled_bookings = cancelled_bookings.reindex(all_dates, fill_value=0)

# Min-max normalize
total_norm = (total_bookings - total_bookings.min()) / (total_bookings.max() - total_bookings.min())
cancelled_norm = (cancelled_bookings - cancelled_bookings.min()) / (cancelled_bookings.max() - cancelled_bookings.min())

# Plot
plt.figure(figsize=(12, 5))
plt.plot(total_norm.index, total_norm.values, label='Total Bookings (scaled)', color='blue')
plt.plot(cancelled_norm.index, cancelled_norm.values, label='Cancellations (scaled)', color='red')

plt.title('Normalized Booking vs Cancellation Trend Over Time')
plt.xlabel('Check-in Date')
plt.ylabel('Scaled Count (0 to 1)')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

unique_properties = bookings_df['property_id'].unique()
num_props = len(unique_properties)
cols = 5  # number of columns in subplot grid
rows = -(-num_props // cols)  # ceiling division

plt.figure(figsize=(20, rows * 3))

for i, prop_id in enumerate(unique_properties, 1):
    prop_data = bookings_df[bookings_df['property_id'] == prop_id]
    daily_bookings = prop_data.groupby('check_in_date').size()

    plt.subplot(rows, cols, i)
    plt.plot(daily_bookings.index, daily_bookings.values, color='blue')
    plt.title(f'Property {prop_id}', fontsize=10)
    plt.xticks(rotation=45)
    plt.tight_layout()

plt.suptitle('Booking Trends Over Time (Each Property)', fontsize=16)
plt.subplots_adjust(top=0.92)
plt.show()

# Step 1: Group by date and platform
bookings_per_platform = bookings_df.groupby(['check_in_date', 'booking_platform']).size().reset_index(name='num_bookings')

# Step 2: Get list of unique platforms
unique_platforms = bookings_df['booking_platform'].unique()

# Step 3: Create subplots
num_platforms = len(unique_platforms)
cols = 3  # adjust to 2, 4, etc. as needed
rows = -(-num_platforms // cols)  # ceiling division

plt.figure(figsize=(cols * 6, rows * 3))

for i, platform in enumerate(unique_platforms, 1):
    platform_data = bookings_df[bookings_df['booking_platform'] == platform]
    daily_bookings = platform_data.groupby('check_in_date').size()

    plt.subplot(rows, cols, i)
    plt.plot(daily_bookings.index, daily_bookings.values, color='green')
    plt.title(f'Platform: {platform}', fontsize=10)
    plt.xlabel('Check-in Date')
    plt.ylabel('Bookings')
    plt.xticks(rotation=45)
    plt.tight_layout()

plt.suptitle('Booking Trends Over Time by Platform', fontsize=16)
plt.subplots_adjust(top=0.92)
plt.show()

# Step 1: Total bookings per date
total_bookings = bookings_df.groupby('check_in_date').size()
all_dates = pd.date_range(start=bookings_df['check_in_date'].min(),
                          end=bookings_df['check_in_date'].max())
total_bookings = total_bookings.reindex(all_dates, fill_value=0)
total_scaled = (total_bookings - total_bookings.min()) / (total_bookings.max() - total_bookings.min())

# Step 2: Unique platforms
unique_platforms = bookings_df['booking_platform'].unique()
num_platforms = len(unique_platforms)
cols = 3
rows = -(-num_platforms // cols)  # ceiling division

# Step 3: Plot each platform against overall
plt.figure(figsize=(cols * 6, rows * 3))

for i, platform in enumerate(unique_platforms, 1):
    platform_data = bookings_df[bookings_df['booking_platform'] == platform]
    daily_platform = platform_data.groupby('check_in_date').size()
    daily_platform = daily_platform.reindex(all_dates, fill_value=0)
    platform_scaled = (daily_platform - daily_platform.min()) / (daily_platform.max() - daily_platform.min())

    plt.subplot(rows, cols, i)
    plt.plot(all_dates, total_scaled.values, label='Overall', color='gray', linestyle='--')
    plt.plot(all_dates, platform_scaled.values, label=platform, color='green')
    plt.title(f'{platform} vs Overall', fontsize=10)
    plt.xlabel('Date')
    plt.ylabel('Scaled Bookings')
    plt.xticks(rotation=45)
    plt.legend(fontsize=8)
    plt.grid(True)
    plt.tight_layout()

plt.suptitle('Platform Booking Trends vs Overall (Scaled)', fontsize=16)
plt.subplots_adjust(top=0.92)
plt.show()

# Step 1: Merge city info into booking data
bookings_with_city = bookings_df.merge(hotel_df[['property_id', 'city']], on='property_id', how='left')

# Step 2: Get unique cities
unique_cities = bookings_with_city['city'].dropna().unique()
all_dates = pd.date_range(start=bookings_df['check_in_date'].min(), end=bookings_df['check_in_date'].max())

# Step 3: Plot per city (with scaling)
cols = 2
rows = -(-len(unique_cities) // cols)
plt.figure(figsize=(cols * 7, rows * 4))

for i, city in enumerate(unique_cities, 1):
    city_data = bookings_with_city[bookings_with_city['city'] == city]

    total = city_data.groupby('check_in_date').size().reindex(all_dates, fill_value=0)
    cancelled = city_data[city_data['booking_status'].str.lower() == 'cancelled']
    cancelled = cancelled.groupby('check_in_date').size().reindex(all_dates, fill_value=0)

    # Min-max scaling
    total_scaled = (total - total.min()) / (total.max() - total.min()) if total.max() > 0 else total
    cancelled_scaled = (cancelled - cancelled.min()) / (cancelled.max() - cancelled.min()) if cancelled.max() > 0 else cancelled

    plt.subplot(rows, cols, i)
    plt.plot(all_dates, total_scaled, label='Bookings (scaled)', color='blue')
    plt.plot(all_dates, cancelled_scaled, label='Cancellations (scaled)', color='red')
    plt.title(f'{city}', fontsize=10)
    plt.xlabel('Date')
    plt.ylabel('Scaled Count')
    plt.xticks(rotation=45)
    plt.legend(fontsize=8)
    plt.grid(True)
    plt.tight_layout()

plt.suptitle('Scaled Booking vs Cancellation Trends by City', fontsize=16)
plt.subplots_adjust(top=0.93)
plt.show()

#Creating new column - occupancy rate in the occupancy sheet
occupancy_df['occupancy_rate'] = (
    occupancy_df['successful_bookings'] / occupancy_df['capacity']
) * 100
occupancy_df['occupancy_rate'] = occupancy_df['occupancy_rate'].round(2)
print(occupancy_df[['occupancy_id', 'date', 'room_category', 'occupancy_rate']].head())

bookings_df['booking_duration'] = (
    pd.to_datetime(bookings_df['checkout_date']) - pd.to_datetime(bookings_df['check_in_date'])
).dt.days

# Preview
print(bookings_df[['booking_id', 'check_in_date', 'checkout_date', 'booking_duration']].head())

bookings_df['total_revenue_generated'] = bookings_df['revenue_generated'] * bookings_df['booking_duration']
bookings_df['total_revenue_realized'] = bookings_df['revenue_realized'] * bookings_df['booking_duration']

# Preview
print(bookings_df[['booking_id', 'revenue_generated', 'revenue_realized', 'booking_duration',
                   'total_revenue_generated', 'total_revenue_realized']].head())

bookings_df['revenue_ratio'] = bookings_df['total_revenue_realized'] / bookings_df['total_revenue_generated'].replace(0, pd.NA)

# Preview
print(bookings_df[['booking_id', 'total_revenue_realized', 'total_revenue_generated', 'revenue_ratio']].head())

bookings_df['days_booked_in_advance'] = (
    pd.to_datetime(bookings_df['check_in_date']) - pd.to_datetime(bookings_df['booking_date'])
).dt.days

# Preview
print(bookings_df[['booking_id', 'booking_date', 'check_in_date', 'days_booked_in_advance']].head())

# Step 1: Filter only cancelled bookings
cancelled = bookings_df[bookings_df['booking_status'].str.lower() == 'cancelled'].copy()

# Step 2: Estimate days cancelled in advance based on booking lead time
def estimate_cancel_days(x):
    """
    Estimations:
    - If booked ≥8 days → cancel ~40% of lead time
    - If booked 2–7 days → ~60%
    - If booked <2 days → ~80%
    Logic uses truncation (int) to avoid rounding up.
    """
    adv = x['days_booked_in_advance']
    if adv >= 8:
        return int(adv * 0.4)
    elif adv >= 2:
        return int(adv * 0.6)
    elif adv >= 0:
        return int(adv * 0.8)
    else:
        return pd.NA  # safeguard

cancelled['days_cancelled_in_advance'] = cancelled.apply(estimate_cancel_days, axis=1)

# Step 3: Compute cancellation date
cancelled['cancellation_date'] = pd.to_datetime(cancelled['check_in_date']) - pd.to_timedelta(cancelled['days_cancelled_in_advance'], unit='D')

# Step 4: Merge back into main DataFrame
bookings_df = bookings_df.merge(
    cancelled[['booking_id', 'days_cancelled_in_advance', 'cancellation_date']],
    on='booking_id',
    how='left'
)

# Step 5: Ensure column is proper integer and missing values show up as blank (NaN)
bookings_df['days_cancelled_in_advance'] = bookings_df['days_cancelled_in_advance'].astype('Int64')  # Pandas nullable integer type

# Preview
print(bookings_df[['booking_id', 'booking_status', 'days_booked_in_advance',
                   'days_cancelled_in_advance', 'cancellation_date']].head(10))

# Filter total bookings and cancelled bookings grouped by platform
total_by_platform = bookings_df.groupby('booking_platform').size()
cancelled_by_platform = bookings_df[bookings_df['booking_status'].str.lower() == 'cancelled'].groupby('booking_platform').size()

# Compute cancellation rate (%)
cancellation_rate = (cancelled_by_platform / total_by_platform) * 100

# Display sorted result
print(cancellation_rate.sort_values(ascending=False).round(2).astype(str) + ' %')

# Total and cancelled bookings per property
total_by_property = bookings_df.groupby('property_id').size()
cancelled_by_property = bookings_df[bookings_df['booking_status'].str.lower() == 'cancelled'].groupby('property_id').size()

# Compute cancellation rate
cancellation_rate = (cancelled_by_property / total_by_property) * 100

# Sort by cancellation rate
cancellation_rate = cancellation_rate.sort_values(ascending=False)

# Plot
plt.figure(figsize=(12, 6))
plt.bar(cancellation_rate.index.astype(str), cancellation_rate.values, color='tomato')
plt.xlabel('Property ID')
plt.ylabel('Cancellation Rate (%)')
plt.title('Cancellation Rate by Property')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# Merge bookings and occupancy on property_id, room_category (room_id), and check-in date
merged = pd.merge(
    bookings_df,
    occupancy_df.rename(columns={'date': 'check_in_date'}),
    on=['property_id', 'room_category', 'check_in_date'],
    how='left'
)

# Calculate new summary DataFrame grouped by property_id and room_id (room_category)
summary_df = merged.groupby(['property_id', 'room_category']).agg({
    'occupancy_rate': 'mean',
    'ratings_given': 'mean',
    'capacity': 'first',
    'revenue_realized': 'sum'
}).reset_index()

# Rename columns for clarity
summary_df.rename(columns={
    'room_category': 'room_id',
    'occupancy_rate': 'avg_occupancy_rate',
    'ratings_given': 'mean_rating',
    'revenue_realized': 'total_revenue_realized'
}, inplace=True)

# Create the primary key: property_room_id
summary_df['property_room_id'] = summary_df['property_id'].astype(str) + summary_df['room_id']

# Reorder columns
summary_df = summary_df[[
    'property_room_id', 'property_id', 'room_id',
    'avg_occupancy_rate', 'mean_rating', 'capacity', 'total_revenue_realized'
]]

# Preview the new sheet
print(summary_df.head())

# Drop missing or infinite values (safety check)
valid_ratios = bookings_df['revenue_ratio'].replace([float('inf'), -float('inf')], pd.NA).dropna()

# Optional: round ratio to 2 decimal places for grouping
rounded_ratios = valid_ratios.round(2)

# Count frequency of each ratio
ratio_counts = rounded_ratios.value_counts().sort_index()

# Plot
plt.figure(figsize=(12, 6))
plt.bar(ratio_counts.index.astype(str), ratio_counts.values, color='steelblue')
plt.xlabel('Revenue Ratio (Realized / Generated)')
plt.ylabel('Number of Bookings')
plt.title('Distribution of Revenue Ratios')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# Step 1: Crosstab of counts per platform and revenue ratio
platform_ratio_counts = pd.crosstab(bookings_df['booking_platform'], bookings_df['revenue_ratio'])

# Step 2: Convert counts to percentages per platform
platform_ratio_pct = platform_ratio_counts.div(platform_ratio_counts.sum(axis=1), axis=0) * 100

# Step 3: Plot
ax = platform_ratio_pct.plot(
    kind='bar',
    stacked=True,
    color={0.4: 'tomato', 1.0: 'seagreen'},
    figsize=(10, 6)
)

plt.ylabel('Percentage of Bookings (%)')
plt.xlabel('Booking Platform')
plt.title('Revenue Ratio Distribution by Booking Platform')
plt.legend(title='Revenue Ratio', labels=['0.40', '1.00'])
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.tight_layout()

# Step 4: Annotate each bar with percentage
for i, platform in enumerate(platform_ratio_pct.index):
    bottom = 0
    for ratio in [0.4, 1.0]:
        value = platform_ratio_pct.loc[platform, ratio]
        if value > 0:
            ax.text(i, bottom + value / 2, f'{value:.0f}%', ha='center', va='center', color='white', fontweight='bold')
            bottom += value

plt.show()

# Step 1: Crosstab of revenue ratio per property
property_ratio_counts = pd.crosstab(bookings_df['property_id'], bookings_df['revenue_ratio'])

# Step 2: Convert to percentages
property_ratio_pct = property_ratio_counts.div(property_ratio_counts.sum(axis=1), axis=0) * 100

# Step 3: Plot stacked bar chart
ax = property_ratio_pct.plot(
    kind='bar',
    stacked=True,
    color={0.4: 'tomato', 1.0: 'seagreen'},
    figsize=(12, 6)
)

plt.ylabel('Percentage of Bookings (%)')
plt.xlabel('Property ID')
plt.title('Revenue Ratio Distribution by Property')
plt.legend(title='Revenue Ratio', labels=['0.40', '1.00'])
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.tight_layout()

# Step 4: Add percentage labels inside bars
for i, prop in enumerate(property_ratio_pct.index):
    bottom = 0
    for ratio in [0.4, 1.0]:
        value = property_ratio_pct.loc[prop, ratio]
        if value > 0:
            ax.text(i, bottom + value / 2, f'{value:.0f}%', ha='center', va='center', color='white', fontweight='bold')
            bottom += value

plt.show()

# Step 1: Crosstab of revenue ratio by booking_status
status_ratio_counts = pd.crosstab(bookings_df['booking_status'], bookings_df['revenue_ratio'])

# Step 2: Convert counts to percentages per status
status_ratio_pct = status_ratio_counts.div(status_ratio_counts.sum(axis=1), axis=0) * 100

# Step 3: Plot stacked bar chart
ax = status_ratio_pct.plot(
    kind='bar',
    stacked=True,
    color={0.4: 'tomato', 1.0: 'seagreen'},
    figsize=(10, 6)
)

plt.ylabel('Percentage of Bookings (%)')
plt.xlabel('Booking Status')
plt.title('Revenue Ratio Distribution by Booking Status')
plt.legend(title='Revenue Ratio', labels=['0.40', '1.00'])
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.tight_layout()

# Step 4: Annotate bars with percentage labels
for i, status in enumerate(status_ratio_pct.index):
    bottom = 0
    for ratio in [0.4, 1.0]:
        value = status_ratio_pct.loc[status, ratio]
        if value > 0:
            ax.text(i, bottom + value / 2, f'{value:.0f}%', ha='center', va='center', color='white', fontweight='bold')
        bottom += value

plt.show()

# Count frequency of each value in days_booked_in_advance
advance_counts = bookings_df['days_booked_in_advance'].value_counts().sort_index()

# Plot
plt.figure(figsize=(12, 6))
plt.bar(advance_counts.index, advance_counts.values, color='steelblue')
plt.xlabel('Days Booked in Advance')
plt.ylabel('Number of Bookings')
plt.title('Booking Lead Time Distribution')
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# Drop missing (non-cancelled) values and convert to integer if needed
cancel_days = bookings_df['days_cancelled_in_advance'].dropna().astype(int)

# Count frequency of each cancellation lead time
cancel_counts = cancel_days.value_counts().sort_index()

# Plot
plt.figure(figsize=(12, 6))
plt.bar(cancel_counts.index, cancel_counts.values, color='indianred')
plt.xlabel('Days Cancelled in Advance')
plt.ylabel('Number of Cancellations')
plt.title('Cancellation Lead Time Distribution')
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# Create a summary table (not saved)
cancel_summary = (
    bookings_df['days_cancelled_in_advance']
    .dropna()
    .astype(int)
    .value_counts()
    .sort_index()
    .reset_index()
)

# Rename columns for readability
cancel_summary.columns = ['Days Cancelled in Advance', 'Number of Cancellations']

# Display the table
print(cancel_summary)

# Scatter plot
plt.figure(figsize=(10, 6))
plt.scatter(
    summary_df['mean_rating'],
    summary_df['avg_occupancy_rate'],
    color='mediumseagreen',
    alpha=0.7
)

plt.xlabel('Mean Rating')
plt.ylabel('Average Occupancy Rate (%)')
plt.title('Mean Rating vs. Average Occupancy Rate')
plt.grid(True, linestyle='--', alpha=0.4)
plt.tight_layout()
plt.show()

# Sorted table by property_id
sorted_summary = summary_df.sort_values(by='property_id')

# Display table
print(sorted_summary[['property_id', 'room_id', 'avg_occupancy_rate', 'mean_rating']])

# Function to compute new revenue and satisfaction under each policy
def compute_policy_values(row):
    # If not cancelled (days_cancelled_in_advance is missing), return original revenue and NaNs for satisfaction
    if pd.isna(row['days_cancelled_in_advance']):
        original = row['total_revenue_generated']
        return pd.Series([original, original, original, pd.NA, pd.NA, pd.NA])

    days = int(row['days_cancelled_in_advance'])
    original = row['total_revenue_generated']

    # Policy 1
    if days <= 1:
        refund1 = 0.10
        score1 = 4
    elif 2 <= days <= 7:
        refund1 = 0.50
        score1 = 8
    else:  # 8+
        refund1 = 0.90
        score1 = 12

    # Policy 2
    if days <= 1:
        refund2 = 0.20
        score2 = 5
    elif 2 <= days <= 7:
        refund2 = 0.50
        score2 = 8
    else:
        refund2 = 0.80
        score2 = 11

    # Policy 3
    if days == 0:
        refund3 = 0.10
        score3 = 3
    elif days in [1, 2]:
        refund3 = 0.30
        score3 = 6
    elif 3 <= days <= 7:
        refund3 = 0.60
        score3 = 9
    else:
        refund3 = 0.90
        score3 = 12

    rev1 = int(original * (1 - refund1))
    rev2 = int(original * (1 - refund2))
    rev3 = int(original * (1 - refund3))

    return pd.Series([rev1, rev2, rev3, score1, score2, score3])

# Apply logic
new_cols = bookings_df.apply(compute_policy_values, axis=1)
new_cols.columns = [
    'policy_1_revenue_realised',
    'policy_2_revenue_realised',
    'policy_3_revenue_realised',
    'policy_1_customer_satisfaction',
    'policy_2_customer_satisfaction',
    'policy_3_customer_satisfaction'
]

# Merge into main dataframe
bookings_df = pd.concat([bookings_df, new_cols], axis=1)

# Ensure integer formatting with nullable integers
for col in new_cols.columns:
    bookings_df[col] = bookings_df[col].astype('Int64')

# Preview output
print(bookings_df[[
    'booking_id', 'total_revenue_generated',
    'policy_1_revenue_realised', 'policy_2_revenue_realised', 'policy_3_revenue_realised',
    'policy_1_customer_satisfaction', 'policy_2_customer_satisfaction', 'policy_3_customer_satisfaction'
]].head(10))

# Clean out all previously created policy columns (safe even if some don't exist)
policy_cols = [
    'policy_1_revenue_realised', 'policy_2_revenue_realised', 'policy_3_revenue_realised',
    'policy_1_customer_satisfaction', 'policy_2_customer_satisfaction', 'policy_3_customer_satisfaction'
]
bookings_df.drop(columns=[col for col in policy_cols if col in bookings_df.columns], inplace=True)

# Original revenue values
original_generated = bookings_df['total_revenue_generated'].sum()
original_realised = bookings_df['total_revenue_realized'].sum()

# Policy revenue realized
policy_1_total = bookings_df['policy_1_revenue_realised'].sum(skipna=True)
policy_2_total = bookings_df['policy_2_revenue_realised'].sum(skipna=True)
policy_3_total = bookings_df['policy_3_revenue_realised'].sum(skipna=True)

# Percentage change compared to original realized revenue
policy_1_pct_diff = ((policy_1_total - original_realised) / original_realised) * 100
policy_2_pct_diff = ((policy_2_total - original_realised) / original_realised) * 100
policy_3_pct_diff = ((policy_3_total - original_realised) / original_realised) * 100

# Satisfaction scores (cancelled bookings only)
avg_sat_1 = bookings_df['policy_1_customer_satisfaction'].mean(skipna=True)
avg_sat_2 = bookings_df['policy_2_customer_satisfaction'].mean(skipna=True)
avg_sat_3 = bookings_df['policy_3_customer_satisfaction'].mean(skipna=True)

# Display
print("📊 Original Revenue Summary")
print(f"→ Total Revenue Generated: ${original_generated:,}")
print(f"→ Total Revenue Realised : ${original_realised:,}\n")

print("💼 Policy Revenue Comparison")
print(f"→ Policy 1 Revenue Realised: ${policy_1_total:,} ({policy_1_pct_diff:+.2f}% change)")
print(f"→ Policy 2 Revenue Realised: ${policy_2_total:,} ({policy_2_pct_diff:+.2f}% change)")
print(f"→ Policy 3 Revenue Realised: ${policy_3_total:,} ({policy_3_pct_diff:+.2f}% change)\n")

print("😊 Average Customer Satisfaction (Cancelled Bookings Only, Max Score = 12)")
print(f"→ Policy 1 Avg Satisfaction: {avg_sat_1:.2f} / 12")
print(f"→ Policy 2 Avg Satisfaction: {avg_sat_2:.2f} / 12")
print(f"→ Policy 3 Avg Satisfaction: {avg_sat_3:.2f} / 12")

# Drop unnecessary policy columns (Policy 1 & 3)
bookings_df.drop(columns=[
    'policy_1_revenue_realised',
    'policy_3_revenue_realised',
    'policy_1_customer_satisfaction',
    'policy_3_customer_satisfaction'
], inplace=True)

# Rename Policy 2 columns
bookings_df.rename(columns={
    'policy_2_revenue_realised': 'total_realised_revenue_new_cancellation_policy',
    'policy_2_customer_satisfaction': 'customer_satisfaction_for_new_policy'
}, inplace=True)

# Preview updated DataFrame
bookings_df[[
    'booking_id',
    'total_realised_revenue_new_cancellation_policy',
    'customer_satisfaction_for_new_policy'
]].head()

