# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_X2dp6r-zDLudkkL-ldZ2dhfTvAKWs2q
"""

# %%capture
!pip install --upgrade --force-reinstall numpy==1.23.5 pandas==1.5.3 scikit-learn==1.1.3 matplotlib==3.6.3 seaborn==0.12.2 xgboost==1.7.5 prophet==1.1 keras==2.10 tensorflow==2.10

# Basic utilities
import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning & Forecasting
from prophet import Prophet
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.cluster import KMeans
from xgboost import XGBClassifier

# Deep Learning (LSTM)
from keras.models import Sequential
from keras.layers import LSTM, Dense

#upload data
from google.colab import files
uploaded = files.upload()

# Use actual names if files were auto-renamed
date_df       = pd.read_csv("dim_date (1).csv")
hotel_df      = pd.read_csv("dim_hotels (1).csv")
room_df       = pd.read_csv("dim_rooms (1).csv")
occupancy_df  = pd.read_csv("fact_aggregated_bookings (1).csv")
bookings_df   = pd.read_csv("fact_bookings (1).csv")

# %% 4. Pre‑processing  ---------------------------------------------------------
## 4‑A. Standardise columns / types
room_df.rename(columns={'room_id': 'room_category'}, inplace=True)
occupancy_df.rename(columns={'check_in_date': 'date'}, inplace=True)

# 👉 make sure the date column is datetime
occupancy_df['date'] = pd.to_datetime(occupancy_df['date'], errors='coerce')

## 4‑B. Primary keys / formats
occupancy_df['date_str']     = occupancy_df['date'].dt.strftime('%b%d%y').str.lower()
occupancy_df['property_str'] = occupancy_df['property_id'].astype(str)
occupancy_df['occupancy_id'] = (
    occupancy_df['date_str'] + occupancy_df['property_str'] + occupancy_df['room_category']
)

occupancy_df = (
    occupancy_df[['occupancy_id', 'property_id', 'room_category',
                  'date', 'successful_bookings', 'capacity']]
    .drop_duplicates()
)

## 4‑C. Derived metrics in occupancy
occupancy_df['occupancy_rate'] = (
    occupancy_df['successful_bookings'] / occupancy_df['capacity'] * 100
).round(2)

## 4‑D. Booking‑level enrichments
for col in ['booking_date', 'check_in_date', 'checkout_date']:
    bookings_df[col] = pd.to_datetime(bookings_df[col], errors='coerce')

bookings_df['booking_duration']       = (bookings_df['checkout_date'] - bookings_df['check_in_date']).dt.days
bookings_df['days_booked_in_advance'] = (bookings_df['check_in_date'] - bookings_df['booking_date']).dt.days
bookings_df['total_revenue_generated'] = bookings_df['revenue_generated'] * bookings_df['booking_duration']
bookings_df['total_revenue_realized']  = bookings_df['revenue_realized']  * bookings_df['booking_duration']
bookings_df['revenue_ratio'] = bookings_df['total_revenue_realized'] \
                               / bookings_df['total_revenue_generated'].replace(0, np.nan)

#%% 5. Heatmap of numeric correlations ------------------------------------------
plt.figure(figsize=(10,8))
num_corr = bookings_df.select_dtypes(include='number').corr()
sns.heatmap(num_corr, annot=True, cmap='coolwarm', fmt='.2f');
plt.title('Correlation Heatmap'); plt.show()

#%% 6. Cancellation-date heuristic ---------------------------------------------
# (Same thresholds: 40 / 60 / 80 %)
def est_cancel_days(adv):
    if adv >= 8: return int(adv*0.4)
    if adv >= 2: return int(adv*0.6)
    if adv >= 0: return int(adv*0.8)
    return np.nan

cancelled = bookings_df[bookings_df['booking_status'].str.lower()=='cancelled'].copy()
cancelled['days_cancelled_in_advance'] = cancelled['days_booked_in_advance'].apply(est_cancel_days)
cancelled['cancellation_date'] = cancelled['check_in_date'] - pd.to_timedelta(cancelled['days_cancelled_in_advance'],'D')
bookings_df = bookings_df.merge(cancelled[['booking_id','days_cancelled_in_advance','cancellation_date']], on='booking_id', how='left')

#%% 7. KPI Summary Table ---------------------------------------------------------
occ_summary = occupancy_df.groupby(['property_id','room_category']).agg(capacity=('capacity','mean'), avg_occupancy_rate=('occupancy_rate','mean')).reset_index()
avg_price   = bookings_df.groupby(['property_id','room_category']).revenue_generated.mean().reset_index().rename(columns={'revenue_generated':'avg_price'})
summary_df  = occ_summary.merge(avg_price, on=['property_id','room_category'])

bookings_df = bookings_df.merge(avg_price,on=['property_id','room_category'])
bookings_df['day_type_price'] = np.where(bookings_df['revenue_generated']<=bookings_df['avg_price'],'weekday','weekend')
price_by_type = bookings_df.groupby(['property_id','room_category','day_type_price']).revenue_generated.mean().unstack().fillna(0).rename(columns={'weekday':'avg_weekday_price','weekend':'avg_weekend_price'}).reset_index()
summary_df = summary_df.merge(price_by_type, on=['property_id','room_category'])

merged = bookings_df.merge(occupancy_df.rename(columns={'date':'check_in_date'}), on=['property_id','room_category','check_in_date'], how='left')
extended = merged.groupby(['property_id','room_category']).agg(mean_rating=('ratings_given','mean'), total_revenue_realized=('revenue_realized','sum')).reset_index()
final_summary = summary_df.merge(extended, on=['property_id','room_category'])
final_summary['property_room_id'] = final_summary['property_id'].astype(str)+final_summary['room_category']

#%% 8. Visual: Ratings vs Occupancy --------------------------------------------
plt.scatter(final_summary['mean_rating'],final_summary['avg_occupancy_rate']);
plt.xlabel('Mean Rating'); plt.ylabel('Avg Occupancy (%)');
plt.title('Rating vs Occupancy'); plt.grid(True); plt.show()

#%% 9. Cancellation Policy Simulation -------------------------------------------
POLICIES = {
    1: {'0-1': 0.10, '2-7': 0.50, '8+': 0.90, 'sat': [4, 8, 12]},
    2: {'0-1': 0.20, '2-7': 0.50, '8+': 0.80, 'sat': [5, 8, 11]},
    3: {'0'  : 0.10, '1-2': 0.30, '3-7': 0.60, '8+': 0.90, 'sat': [3, 6, 9, 12]}
}

def bucket(d, key_list):
    for k in key_list:
        if k.endswith('+'):                # "8+"
            if d >= int(k[:-1]):
                return k
        elif '-' in k:                     # "lo-hi"
            lo, hi = map(int, k.split('-'))
            if lo <= d <= hi:
                return k
        else:                              # single value like "0"
            if d == int(k):
                return k
    return None

def policy_calc(row):
    if pd.isna(row['days_cancelled_in_advance']):
        return pd.Series({
            'p1_rev': row['total_revenue_generated'],
            'p2_rev': row['total_revenue_generated'],
            'p3_rev': row['total_revenue_generated'],
            'p1_sat': np.nan,
            'p2_sat': np.nan,
            'p3_sat': np.nan
        })

    d        = int(row['days_cancelled_in_advance'])
    original = row['total_revenue_generated']
    out      = {}

    for pid, pol in POLICIES.items():
        key_list = [k for k in pol if k != 'sat']
        b        = bucket(d, key_list)     # find bucket string
        refund   = pol[b]
        sat_idx  = key_list.index(b)       # same order as sat list
        sat      = pol['sat'][sat_idx]

        out[f'p{pid}_rev'] = int(original * (1 - refund))
        out[f'p{pid}_sat'] = sat

    return pd.Series(out)

# Apply and merge the policy calculations
pvals       = bookings_df.apply(policy_calc, axis=1)
bookings_df = pd.concat([bookings_df, pvals], axis=1)

# Choose Policy 2 results
bookings_df['total_realised_revenue_new_cancellation_policy'] = bookings_df['p2_rev']
bookings_df['customer_satisfaction_for_new_policy']           = bookings_df['p2_sat']

#%% 10. Stay / Advance / Occupancy Matrices -------------------------------------
# stay_dates_matrix
a = bookings_df.apply(lambda r:[(r['check_in_date']+pd.Timedelta(days=i)).date() for i in range(r['booking_duration'])],axis=1)
bookings_df['stay_dates_matrix'] = a

# days booked in advance matrix
b = bookings_df.apply(lambda r:[(d - r['booking_date'].date()).days for d in r['stay_dates_matrix']],axis=1)
bookings_df['days_booked_in_advance_matrix'] = b

# occupied_rooms_matrix (increment / decrement algorithm)
tracker = {}
matrices = []
for _,r in bookings_df.sort_values(['booking_date']).iterrows():
    pid,room = r['property_id'],r['room_category']
    seq = []
    for d in r['stay_dates_matrix']:
        key=(pid,room,d)
        tracker[key]=tracker.get(key,0)+1 if r['booking_status'].lower()!='cancelled' else tracker.get(key,0)-1
        seq.append(tracker[key])
    matrices.append(seq)
bookings_df['occupied_rooms_matrix'] = matrices

# occupancy_rate_matrix
cap_lookup = {(row.property_id,row.room_category):row.capacity for _,row in occupancy_df.iterrows()}
bookings_df['occupancy_rate_matrix'] = bookings_df.apply(lambda r:[round(c/cap_lookup.get((r.property_id,r.room_category),1)*100,2) for c in r['occupied_rooms_matrix']],axis=1)

#%% 11. Prophet Forecast ---------------------------------------------------------
print("\n📈 Prophet daily-booking forecast …")
# daily bookings
prop_df = bookings_df.groupby('check_in_date').size().reset_index(name='y').rename(columns={'check_in_date':'ds'})
model = Prophet(yearly_seasonality=True, weekly_seasonality=True)
model.fit(prop_df)
future = model.make_future_dataframe(periods=30)
fcst = model.predict(future)
model.plot(fcst); plt.title('Prophet Forecast – Daily Bookings'); plt.show()

#%% 12. LSTM Forecast ------------------------------------------------------------
print("📈 LSTM forecast … (may take 1-2 min)")
series = prop_df['y'].values.reshape(-1,1)
scaler = MinMaxScaler(); series_scaled = scaler.fit_transform(series)
window = 60; X,y=[],[]
for i in range(len(series_scaled)-window): X.append(series_scaled[i:i+window]), y.append(series_scaled[i+window])
X,y=np.array(X),np.array(y)
X=X.reshape((X.shape[0],X.shape[1],1))
train_end=int(len(X)*0.8)
X_train,X_test,y_train,y_test=X[:train_end],X[train_end:],y[:train_end],y[train_end:]
model_lstm = Sequential([LSTM(50,activation='relu',input_shape=(window,1)), Dense(1)])
model_lstm.compile(optimizer='adam',loss='mse')
model_lstm.fit(X_train,y_train,epochs=20,batch_size=16,verbose=0)
last_seq = series_scaled[-window:]
preds=[]; cur=last_seq.copy()
for _ in range(30):
    p=model_lstm.predict(cur.reshape(1,window,1),verbose=0)[0,0]
    preds.append(p)
    cur=np.vstack([cur[1:],[[p]]])
forecast_dates = pd.date_range(start=prop_df.ds.max() + pd.Timedelta(days=1), periods=30, freq='D')
plt.plot(forecast_dates, scaler.inverse_transform(np.array(preds).reshape(-1,1)))
plt.title('LSTM Forecast – Next 30 Days'); plt.xticks(rotation=45); plt.show()

#%% 13. Cancellation-Risk (XGBoost) --------------------------------------------
print("\n🔍 Cancellation risk model …")
df_c = bookings_df.copy(); df_c['cancel_flag']=(df_c.booking_status.str.lower()=='cancelled').astype(int)
use_cols=['days_booked_in_advance','total_revenue_generated','property_id','room_category','booking_platform']
df_c=df_c[use_cols+['cancel_flag']].dropna()
df_c=pd.get_dummies(df_c,columns=['property_id','room_category','booking_platform'],drop_first=True)
X,y=df_c.drop('cancel_flag',axis=1), df_c['cancel_flag']
X_tr,X_te,y_tr,y_te=train_test_split(X,y,test_size=0.2,stratify=y,random_state=42)
clf=XGBClassifier(use_label_encoder=False,eval_metric='logloss'); clf.fit(X_tr,y_tr)
print(classification_report(y_te,clf.predict(X_te)))

#%% 14. Price-Occupancy Elasticity (Random-Forest) ------------------------------
print("\n💰 Price->Occupancy elasticity model …")

price_df = bookings_df.groupby(
    ['property_id', 'room_category', 'check_in_date']
).agg(avg_price=('revenue_generated', 'mean')).reset_index()

merged_occ = occupancy_df.merge(
    price_df,
    left_on=['property_id', 'room_category', 'date'],
    right_on=['property_id', 'room_category', 'check_in_date'],
    how='left'
).dropna(subset=['avg_price'])

merged_occ['dow'] = merged_occ['date'].dt.weekday
merged_occ = pd.get_dummies(
    merged_occ,
    columns=['dow', 'property_id', 'room_category'],
    drop_first=True
)

Xp = merged_occ.drop(columns=[
    'occupancy_id', 'date', 'successful_bookings',
    'capacity', 'occupancy_rate', 'check_in_date'
])
yp = merged_occ['occupancy_rate']

Xp_tr, Xp_te, yp_tr, yp_te = train_test_split(Xp, yp, test_size=0.25, random_state=42)
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(Xp_tr, yp_tr)

# Calculate RMSE manually
mse = mean_squared_error(yp_te, rf.predict(Xp_te))
rmse = np.sqrt(mse)
print("RMSE:", round(rmse, 2), "%")

#%% 15. Customer Segmentation (K-Means) -----------------------------------------
print("\n👥 Guest segmentation …")
seg_df = bookings_df[['days_booked_in_advance','revenue_generated']].dropna()
km=KMeans(n_clusters=3,random_state=42).fit(seg_df)
seg_df['segment']=km.labels_
print(seg_df.segment.value_counts())









